# Profiling and running an ML algorithm on the US Census Dataset

In [ ]:
#Importing required packages.
import pandas as pd

%matplotlib inline

In [ ]:
url="https://archive.ics.uci.edu/ml/machine-learning-databases/statlog/german/german.data"

df = pd.read_table(filepath_or_buffer=url, names = ['status', 'month', 'credit-history',
'purpose', 'credit-amount', 'savings', 'employment', 'investment-as-income-percentage', 'sex-status',
 'other-debtors', 'residence-since', 'property', 'age', 'installment-plans', 'housing',
 'number-of-credits',  'skill-level', 'people-liable-for', 'telephone', 'foreign-worker',
 'credit'
], sep=" ")

df.reset_index(drop=True, inplace=True)

df.head()

,status,month,credit-history,purpose,credit-amount,savings,employment,investment-as-income-percentage,sex-status,other-debtors,...,property,age,installment-plans,housing,number-of-credits,skill-level,people-liable-for,telephone,foreign-worker,credit
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,...,A121,67,A143,A152,2,A173,1,A192,A201,1
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,...,A121,22,A143,A152,1,A173,1,A191,A201,2
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,...,A121,49,A143,A152,1,A172,2,A191,A201,1
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,...,A122,45,A143,A153,1,A173,2,A191,A201,1
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,...,A124,53,A143,A153,2,A173,2,A191,A201,2

In [ ]:
df['credit'] = df['credit'].replace(1, 'Good Credit')
df['credit'] = df['credit'].replace(2, 'Bad Credit')

In [ ]:
df['sex'] = df['sex-status'].replace({'A91': 'Male', 'A93': 'Male', 'A94': 'Male'})
df['sex'] = df['sex'].replace({'A92': 'Female', 'A95': 'Female'})

df.drop(['sex-status'], axis=1, inplace=True)

In [ ]:
df.head()

,status,month,credit-history,purpose,credit-amount,savings,employment,investment-as-income-percentage,other-debtors,residence-since,...,age,installment-plans,housing,number-of-credits,skill-level,people-liable-for,telephone,foreign-worker,credit,sex
0,A11,6,A34,A43,1169,A65,A75,4,A101,4,...,67,A143,A152,2,A173,1,A192,A201,Good Credit,Male
1,A12,48,A32,A43,5951,A61,A73,2,A101,2,...,22,A143,A152,1,A173,1,A191,A201,Bad Credit,Female
2,A14,12,A34,A46,2096,A61,A74,2,A101,3,...,49,A143,A152,1,A172,2,A191,A201,Good Credit,Male
3,A11,42,A32,A42,7882,A61,A74,2,A103,4,...,45,A143,A153,1,A173,2,A191,A201,Good Credit,Male
4,A11,24,A33,A40,4870,A61,A73,3,A101,4,...,53,A143,A153,2,A173,2,A191,A201,Bad Credit,Male

In [ ]:
bins = [0, 26, 120]
labels = ['Young', 'Old']

df['age'] = pd.cut(df['age'], bins=bins, labels=labels)

In [ ]:
df.head()

,status,month,credit-history,purpose,credit-amount,savings,employment,investment-as-income-percentage,other-debtors,residence-since,...,age,installment-plans,housing,number-of-credits,skill-level,people-liable-for,telephone,foreign-worker,credit,sex
0,A11,6,A34,A43,1169,A65,A75,4,A101,4,...,Old,A143,A152,2,A173,1,A192,A201,Good Credit,Male
1,A12,48,A32,A43,5951,A61,A73,2,A101,2,...,Young,A143,A152,1,A173,1,A191,A201,Bad Credit,Female
2,A14,12,A34,A46,2096,A61,A74,2,A101,3,...,Old,A143,A152,1,A172,2,A191,A201,Good Credit,Male
3,A11,42,A32,A42,7882,A61,A74,2,A103,4,...,Old,A143,A153,1,A173,2,A191,A201,Good Credit,Male
4,A11,24,A33,A40,4870,A61,A73,3,A101,4,...,Old,A143,A153,2,A173,2,A191,A201,Bad Credit,Male

In [ ]:
df.to_csv('german.csv', index=False)